# Generated by Django 3.1.1 on 2020-09-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(verbose_name='date published')),
                ('bucket_link', models.CharField(max_length=200)),
            ],
        ),
    ]
